#!/usr/bin/env node
// Compresses web/index.html into firmware/ledmatrix/web_assets.h (gzip PROGMEM array).
// --check: fails when the committed header does not match the sources (compares decompressed
// content, since zlib builds on different OSes produce different gzip bytes).
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { gzipSync, gunzipSync } from 'node:zlib';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'web/index.html');
const out = join(root, 'firmware/ledmatrix/web_assets.h');

const html = readFileSync(src);

function parseHeader(text) {
  const m = text.match(/WEB_INDEX_GZ\[\] PROGMEM = \{([\s\S]*?)\};/);
  if (!m) return null;
  return Buffer.from(m[1].split(',').map((s) => s.trim()).filter(Boolean).map((s) => parseInt(s, 16)));
}

if (process.argv.includes('--check')) {
  if (!existsSync(out)) {
    console.error('web_assets.h missing: run make gen');
    process.exit(1);
  }
  const gz = parseHeader(readFileSync(out, 'utf8'));
  if (!gz || !gunzipSync(gz).equals(html)) {
    console.error('web_assets.h is stale: run make gen');
    process.exit(1);
  }
  console.log('web_assets.h up to date');
  process.exit(0);
}

const gz = gzipSync(html, { level: 9 });
const lines = [];
for (let i = 0; i < gz.length; i += 20) {
  lines.push('  ' + [...gz.subarray(i, i + 20)].map((b) => '0x' + b.toString(16).padStart(2, '0')).join(', ') + ',');
}
const header = `// GENERATED by tools/gen_web.mjs from web/index.html. Do not edit; run \`make gen\`.
#pragma once
#include <Arduino.h>

static const size_t WEB_INDEX_GZ_LEN = ${gz.length};
static const uint8_t WEB_INDEX_GZ[] PROGMEM = {
${lines.join('\n')}
};
`;
writeFileSync(out, header);
console.log(`web_assets.h: ${html.length} -> ${gz.length} bytes gzip`);
