#!/usr/bin/env node
// Generates firmware/ledmatrix/font5x7.h from shared/font5x7.json, the single source of the font
// used by the firmware, the landing demo and the social card.
// --check: fails when the committed header does not match the JSON.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'shared/font5x7.json');
const out = join(root, 'firmware/ledmatrix/font5x7.h');
const ASCII_GLYPHS = 95;

const font = JSON.parse(readFileSync(src, 'utf8'));
const hex = (v) => '0x' + v.toString(16).toUpperCase().padStart(2, '0');
const rows = [];
font.glyphs.forEach((g, i) => {
  if (g.cols.length !== font.width || g.cols.some((c) => c < 0 || c >= 1 << font.height))
    throw new Error(`glyph ${i} (${g.label}) is not ${font.width}x${font.height}`);
  if (i === ASCII_GLYPHS) rows.push('    // Extra glyphs (index 95+)');
  rows.push(`    {${g.cols.map(hex).join(', ')}},  // ${g.label}`);
});

const header = `// GENERATED by tools/gen_assets.mjs from shared/font5x7.json. Do not edit; run \`make gen\`.
// 5x7 bitmap font. Each glyph is 5 columns, LSB = top row.
// Glyphs 0..94 map to ASCII 0x20..0x7E; the rest are extra glyphs for Spanish text.
#pragma once
#include <stdint.h>

static const uint8_t FONT5X7[][5] = {
${rows.join('\n')}
};

static const uint8_t FONT_GLYPH_COUNT = sizeof(FONT5X7) / 5;
static const uint8_t FONT_GLYPH_UNKNOWN = '?' - 0x20;
`;

if (process.argv.includes('--check')) {
  if (!existsSync(out) || readFileSync(out, 'utf8') !== header) {
    console.error('font5x7.h is stale: run make gen');
    process.exit(1);
  }
  console.log('font5x7.h up to date');
  process.exit(0);
}
writeFileSync(out, header);
console.log(`font5x7.h: ${font.glyphs.length} glyphs`);
